// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3jk0pJv4IOnPQ9kB7NrD7e4e0RE8c9hU',
    appId: '1:333545597291:web:1b98aec42db3a71e43c42e',
    messagingSenderId: '333545597291',
    projectId: 'heatmap-102a9',
    authDomain: 'heatmap-102a9.firebaseapp.com',
    databaseURL: 'https://heatmap-102a9-default-rtdb.firebaseio.com',
    storageBucket: 'heatmap-102a9.firebasestorage.app',
    measurementId: 'G-6XNL182466',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuj-UXqbbVU_shh3VtMihm8kdKT8Y9ea4',
    appId: '1:333545597291:android:df2081af854f6ea743c42e',
    messagingSenderId: '333545597291',
    projectId: 'heatmap-102a9',
    databaseURL: 'https://heatmap-102a9-default-rtdb.firebaseio.com',
    storageBucket: 'heatmap-102a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyFOaGdjDnbk8YdBK88PZ0fuKCfsH-qa4',
    appId: '1:333545597291:ios:402b628d6e79b93c43c42e',
    messagingSenderId: '333545597291',
    projectId: 'heatmap-102a9',
    databaseURL: 'https://heatmap-102a9-default-rtdb.firebaseio.com',
    storageBucket: 'heatmap-102a9.firebasestorage.app',
    iosBundleId: 'com.example.heatMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyFOaGdjDnbk8YdBK88PZ0fuKCfsH-qa4',
    appId: '1:333545597291:ios:402b628d6e79b93c43c42e',
    messagingSenderId: '333545597291',
    projectId: 'heatmap-102a9',
    databaseURL: 'https://heatmap-102a9-default-rtdb.firebaseio.com',
    storageBucket: 'heatmap-102a9.firebasestorage.app',
    iosBundleId: 'com.example.heatMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3jk0pJv4IOnPQ9kB7NrD7e4e0RE8c9hU',
    appId: '1:333545597291:web:29769fb75a286b2143c42e',
    messagingSenderId: '333545597291',
    projectId: 'heatmap-102a9',
    authDomain: 'heatmap-102a9.firebaseapp.com',
    databaseURL: 'https://heatmap-102a9-default-rtdb.firebaseio.com',
    storageBucket: 'heatmap-102a9.firebasestorage.app',
    measurementId: 'G-L9YF9CSL0S',
  );
}
