name: HEAT_MAP
description: "A Flutter app to display live location on a Mapbox map."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1 # Latest version for map display
  location: ^8.0.0 # For live location updates
  permission_handler: ^11.4.0 # For location permissions
  latlong2: ^0.9.1 # Corrected to the latest version
  google_maps_flutter: ^2.12.1
  firebase_data_connect: ^0.1.4
  cloud_firestore: ^5.6.6
  curved_navigation_bar: ^1.0.6
  geolocator: ^14.0.0
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true